-- Insert rows into the "user_event_subscription" table
INSERT INTO user_service_schema.user_event_subscription (user_id, event_id, created_at)
VALUES (1, 1, current_timestamp),
       (1, 2, current_timestamp),
       (2, 1, current_timestamp),
       (2, 3, current_timestamp),
       (3, 2, current_timestamp),
       (3, 4, current_timestamp),
       (4, 1, current_timestamp),
       (4, 3, current_timestamp),
       (5, 2, current_timestamp),
       (5, 5, current_timestamp),
       (6, 3, current_timestamp),
       (6, 6, current_timestamp),
       (7, 4, current_timestamp),
       (7, 7, current_timestamp),
       (8, 5, current_timestamp),
       (8, 8, current_timestamp),
       (9, 6, current_timestamp),
       (9, 9, current_timestamp),
       (10, 7, current_timestamp),
       (10, 10, current_timestamp);

-- Insert rows into the "user_category_subscription" table
INSERT INTO user_service_schema.user_category_subscription (user_id, category_id, created_at)
VALUES (1, 1, current_timestamp),
       (1, 2, current_timestamp),
       (2, 2, current_timestamp),
       (2, 3, current_timestamp),
       (3, 3, current_timestamp),
       (3, 4, current_timestamp),
       (4, 4, current_timestamp),
       (4, 5, current_timestamp),
       (5, 5, current_timestamp),
       (5, 6, current_timestamp),
       (6, 6, current_timestamp),
       (6, 1, current_timestamp),
       (7, 1, current_timestamp),
       (7, 2, current_timestamp),
       (8, 2, current_timestamp),
       (8, 3, current_timestamp),
       (9, 3, current_timestamp),
       (9, 4, current_timestamp),
       (10, 4, current_timestamp),
       (10, 5, current_timestamp);